# -*- coding: utf-8 -*-
"""data sets ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrWQ2oFpdPmXJ-JlMGcQoB8kSsTwBQ_Q
"""

E = {0, 2, 4, 6, 8};
 N = {1, 2, 3, 4, 5};

print("Union :", E | N)

print("Intersection :", E & N)

print("Difference :", E - N)

print("Symmetric difference :", E ^ N)