# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JAoBGxJf1fmJOWis8zIWkzWpBF2Ns6e
"""

list1 = [12, -7, 5, 64, -14]
for num in list1:
     if  num >= 0:
              print (num, end = " ")

list2 = [12, 14, -95, 3]
for num in list2:
  if num >= 0:
    print (num,end = " ")